var mongoose = require('mongoose'); 
// Photo model consists of:
// filename (generated by multer upon file upload to prevent file overwrites of duplicates)
// original filename (for display)
// tags: optional array of string tags that describe the photo 
var PhotoSchema = new mongoose.Schema({
  filename: {
    type: String,
    required: true
  },
  originalname: {
    type: String,
    required: true
  },
  tags: [{
    type: String
  }]
});
var Photo = mongoose.model('Photo', PhotoSchema);
module.exports = Photo;